[FEATURE] Ata do dia 10/11
Interacao-Humano-Computador/2022.2-Lichess pull request #6
Opened 2022-11-11 20:58 UTC by nszchagas

O que foi feito:

- Inclusão da ata escrita pelo @Luckx98, já na versão revisada, na estrutura dos docs. 
- Alteração da tabela da seção about us para remover o integrante que retirou a disciplina e inclusão do meu sobrenome.

2022-11-12 11:05 UTC, Luckx98 requested changes
No documento de ata 10/11, ficou faltando a adição do meu sobrenome no autor, visto que temos dois Lucas na equipe, só para diferenciar mesmo

2022-11-13 13:23 UTC, nszchagas commented
> No documento de ata 10/11, ficou faltando a adição do meu sobrenome no autor, visto que temos dois Lucas na equipe, só para diferenciar mesmo

Resolvido!

2022-11-13 13:47 UTC, MauricioMachadoFF approved these changes

2022-11-17 12:33 UTC, Luckx98 approved these changes

2022-11-17 12:36 UTC, merged