Feat / Add tools
Interacao-Humano-Computador/2022.2-Lichess pull request #9
Opened 2022-11-16 22:25 UTC by Luckx98

2022-11-16 23:53 UTC, nszchagas requested changes
Quando rodei o mkdocs localmente as imagens das ferramentas ficaram quebradas: 
![image](https://user-images.githubusercontent.com/68018675/202320091-e0613550-5ee3-4772-bcbe-e5fa7cf5a602.png)

2022-11-16 23:54 UTC, nszchagas requested changes

2022-11-16 23:54 UTC, nszchagas commented on docs/tools.md
> +<p> As ferramentas foram escolhidas visando a fácil interação dos integrantes do grupo em contexto remoto, tanto assíncrono quanto síncrono. Também foi levado em consideração o nível de familiaridade
Tem um erro de digitação aqui na palavra diminuir.

2022-11-16 23:58 UTC, nszchagas commented on mkdocs.yml
> +    - "Ferramentas": "tools.md"
Vamos manter uma organização nas pastas igual à dos menus na página? Sugiro colocar o arquivo tools.md e a a pasta de imagens dentro da pasta "planejamento".

2022-11-18 01:12 UTC, Luckx98 commented
> Quando rodei o mkdocs localmente as imagens das ferramentas ficaram quebradas: ![image](https://user-images.githubusercontent.com/68018675/202320091-e0613550-5ee3-4772-bcbe-e5fa7cf5a602.png)

Resolvido

2022-11-18 01:13 UTC, Luckx98 reviewed
Resolvido as mudanças

2022-11-18 10:28 UTC, lucasgabriel-2 commented on docs/planejamento/tools.md
> +## 2. Introdução
Repetição do título do tópico

2022-11-18 10:29 UTC, lucasgabriel-2 commented on docs/planejamento/tools.md
> +## 3. Ferramentas utilizadas
Adicionar o youtube como ferramenta para hospedagem das gravações das reuniões

2022-11-18 10:30 UTC, lucasgabriel-2 commented on docs/planejamento/tools.md
> +|  ![Github](../img/github-icon.png)  |       Github       | Será utilizado como repositório dos documentos produzidos e para o versionamento dos mesmos.
Apenas um detalhe, mas acredito que fique melhor da seguinte forma: "Utilizado como repositório dos documentos produzidos e para o versionamento dos mesmos."

2022-11-18 10:32 UTC, lucasgabriel-2 commented on docs/planejamento/tools.md
> +|  ![VsCode](../img/vscode-icon.png) >  | Visual Studio Code | O Visual Studio Code (VsCode) será utilizado para manipulação dos arquivos do projeto, devido facilidade de integração de extensões e da
Apagar o simbolo ">"

2022-11-18 10:34 UTC, lucasgabriel-2 commented on docs/planejamento/tools.md
> +|  ![VsCode](../img/vscode-icon.png) >  | Visual Studio Code | O Visual Studio Code (VsCode) será utilizado para manipulação dos arquivos do projeto, devido facilidade de integração de extensões e da
Apenas um detalhe, mas acredito que fique melhor da seguinte forma: "Utilizado para manipulação dos arquivos do projeto, devido facilidade de integração de extensões e da experiência da maioria dos integrantes com essa ferramenta."

2022-11-18 11:52 UTC, Luckx98 commented on docs/planejamento/tools.md
> +## 3. Ferramentas utilizadas
Resolvido

2022-11-18 14:18 UTC, nszchagas approved these changes

2022-11-18 14:18 UTC, merged